In [1]:
import pandas as pd
import numpy as np
import os

In [4]:
customers_path = r"C:\Users\tania\Customer_Churn_Analysis\data\raw\Customers.xlsx"
orders_path = r"C:\Users\tania\Customer_Churn_Analysis\data\raw\Orders.xlsx"
deliveries_path = r"C:\Users\tania\Customer_Churn_Analysis\data\raw\Deliveries.xlsx"
marketing_path = r"C:\Users\tania\Customer_Churn_Analysis\data\raw\Marketing_Campaigns.xlsx"

In [6]:
customers = pd.read_excel(customers_path)
orders = pd.read_excel(orders_path)
deliveries = pd.read_excel(deliveries_path)
marketing = pd.read_excel(marketing_path)

print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Deliveries:", deliveries.shape)
print("Marketing Campaigns:", marketing.shape)

Customers: (1864, 14)
Orders: (13225, 14)
Deliveries: (12674, 11)
Marketing Campaigns: (3900, 14)

In [7]:
print("CUSTOMERS COLUMNS")
print(customers.columns.tolist())

print("\nORDERS COLUMNS")
print(orders.columns.tolist())

print("\nDELIVERIES COLUMNS")
print(deliveries.columns.tolist())

print("\nMARKETING CAMPAIGNS COLUMNS")
print(marketing.columns.tolist())

CUSTOMERS COLUMNS
['customer_id', 'customer_name', 'gender', 'age', 'email', 'city', 'state', 'region', 'city_tier', 'signup_date', 'acquisition_channel', 'email_opt_in', 'loyalty_member', 'preferred_device']

ORDERS COLUMNS
['order_id', 'customer_id', 'order_date', 'order_status', 'product_category', 'quantity', 'unit_price', 'discount_pct', 'coupon_code', 'order_value', 'shipping_fee', 'payment_method', 'order_channel', 'campaign_id']

DELIVERIES COLUMNS
['delivery_id', 'order_id', 'courier_partner', 'delivery_zone', 'ship_date', 'promised_delivery_date', 'actual_delivery_date', 'delivery_status', 'delivery_attempts', 'courier_charge', 'delivery_rating']

MARKETING CAMPAIGNS COLUMNS
['campaign_record_id', 'campaign_id', 'campaign_name', 'campaign_type', 'channel', 'customer_id', 'sent_date', 'discount_offered_pct', 'cost_per_send', 'opened', 'clicked', 'converted', 'conversion_order_id', 'unsubscribed']

In [8]:
display(customers.head())
display(orders.head())
display(deliveries.head())
display(marketing.head())

,customer_id,customer_name,gender,age,email,city,state,region,city_tier,signup_date,acquisition_channel,email_opt_in,loyalty_member,preferred_device
0,C0001,Shweta Mishra,Female,38.0,shweta.mishra100@example.com,Bengaluru,Karnataka,South,Metro,2023-01-01,Paid Ads,Yes,No,Android
1,C0002,Sneha Ali,Female,24.0,sneha.ali101@example.com,Bhopal,Madhya Pradesh,Central,Tier-2,2023-01-01,Social Media,Yes,Yes,iOS
2,C0003,Akash Trivedi,Male,35.0,akash.trivedi102@example.com,Lucknow,Uttar Pradesh,North,Tier-2,2023-01-01,Organic Search,Yes,No,Android
3,C0004,Radhika Pandey,Female,30.0,radhika.pandey103@example.com,Udaipur,Rajasthan,North,Tier-3,2023-01-02,Organic Search,No,No,Android
4,C0005,Bhavna Sethi,Female,22.0,bhavna.sethi104@example.com,Udaipur,Rajasthan,North,Tier-3,2023-01-03,Organic Search,No,Yes,Android

,order_id,customer_id,order_date,order_status,product_category,quantity,unit_price,discount_pct,coupon_code,order_value,shipping_fee,payment_method,order_channel,campaign_id
0,ORD000001,C0001,2023-01-01,Delivered,Electronics,1,1199,0.0,NaN,1199.00,0,Credit Card,Website,NaN
1,ORD000002,C0009,2023-01-07,Delivered,Electronics,1,2869,20.0,NaN,2295.20,0,Credit Card,Website,NaN
2,ORD000003,C0007,2023-01-08,Returned,Fashion,3,649,10.0,NaN,1752.30,0,Credit Card,Website,NaN
3,ORD000004,C0008,2023-01-11,Delivered,Books & Stationery,1,939,0.0,NaN,939.00,0,UPI,Mobile App,NaN
4,ORD000005,C0002,2023-01-12,Delivered,Sports & Fitness,1,1559,25.0,NaN,1169.25,0,Credit Card,Mobile App,NaN

,delivery_id,order_id,courier_partner,delivery_zone,ship_date,promised_delivery_date,actual_delivery_date,delivery_status,delivery_attempts,courier_charge,delivery_rating
0,DLV000001,ORD000001,SwiftShip,Metro,2023-01-01,2023-01-03,2023-01-03,Delivered,1,44.9,NaN
1,DLV000002,ORD000002,QuickCourier,Tier-2,2023-01-07,2023-01-10,2023-01-10,Delivered,1,51.0,5.0
2,DLV000003,ORD000003,SwiftShip,Metro,2023-01-09,2023-01-12,2023-01-12,Delivered,1,34.1,NaN
3,DLV000004,ORD000004,RoadRunner Logistics,Tier-3,2023-01-12,2023-01-18,2023-01-18,Delivered,1,68.3,NaN
4,DLV000005,ORD000005,QuickCourier,Tier-2,2023-01-12,2023-01-16,2023-01-15,Delivered,1,50.5,NaN

,campaign_record_id,campaign_id,campaign_name,campaign_type,channel,customer_id,sent_date,discount_offered_pct,cost_per_send,opened,clicked,converted,conversion_order_id,unsubscribed
0,CR000001,CMP001,Welcome Series,Welcome,SMS,C0003,2023-01-01,10,0.18,No,No,No,NaN,No
1,CR000002,CMP001,Welcome Series,Welcome,Push Notification,C0004,2023-01-02,10,0.05,No,No,No,NaN,No
2,CR000003,CMP001,Welcome Series,Welcome,Email,C0001,2023-01-03,10,NaN,Yes,No,No,NaN,No
3,CR000004,CMP001,Welcome Series,Welcome,Email,C0006,2023-01-03,10,0.25,Yes,Yes,No,NaN,No
4,CR000005,CMP001,Welcome Series,Welcome,WhatsApp,C0005,2023-01-05,10,0.80,Yes,Yes,No,NaN,No

In [9]:
# Check missing values

print("=== CUSTOMERS ===")
display(customers.isnull().sum())

print("\n=== ORDERS ===")
display(orders.isnull().sum())

print("\n=== DELIVERIES ===")
display(deliveries.isnull().sum())

print("\n=== MARKETING CAMPAIGNS ===")
display(marketing.isnull().sum())

=== CUSTOMERS ===

customer_id             0
customer_name           0
gender                 28
age                    37
email                   0
city                    0
state                   0
region                  0
city_tier               0
signup_date             0
acquisition_channel     0
email_opt_in           18
loyalty_member          0
preferred_device        0
dtype: int64

=== ORDERS ===

order_id                0
customer_id             0
order_date              0
order_status            0
product_category        0
quantity                0
unit_price              0
discount_pct          397
coupon_code          9399
order_value             0
shipping_fee            0
payment_method          0
order_channel          66
campaign_id         13122
dtype: int64

=== DELIVERIES ===

delivery_id                  0
order_id                     0
courier_partner              0
delivery_zone                0
ship_date                    0
promised_delivery_date       0
actual_delivery_date       276
delivery_status              0
delivery_attempts            0
courier_charge               0
delivery_rating           6423
dtype: int64

=== MARKETING CAMPAIGNS ===

campaign_record_id         0
campaign_id                0
campaign_name              0
campaign_type              0
channel                   58
customer_id                0
sent_date                  0
discount_offered_pct       0
cost_per_send             79
opened                     0
clicked                    0
converted                  0
conversion_order_id     3797
unsubscribed               0
dtype: int64

In [10]:
# check duplicates 
print("Duplicate customer records:", customers.duplicated().sum())
print("Duplicate order records:", orders.duplicated().sum())
print("Duplicate delivery records:", deliveries.duplicated().sum())
print("Duplicate marketing records:", marketing.duplicated().sum())

Duplicate customer records: 14
Duplicate order records: 12
Duplicate delivery records: 8
Duplicate marketing records: 10

In [11]:
print("Unique customers:", customers["customer_id"].nunique())
print("Unique orders:", orders["order_id"].nunique())
print("Unique delivery IDs:", deliveries["delivery_id"].nunique())
print("Unique campaigns:", marketing["campaign_id"].nunique())

Unique customers: 1850
Unique orders: 13213
Unique delivery IDs: 12666
Unique campaigns: 48

In [12]:
print("Customers in Orders:", orders["customer_id"].nunique())
print("Customers in Marketing:", marketing["customer_id"].nunique())
print("Orders in Deliveries:", deliveries["order_id"].nunique())

Customers in Orders: 1711
Customers in Marketing: 1753
Orders in Deliveries: 12666

In [13]:
#check duplicate ID
print("Duplicate customer IDs:", customers["customer_id"].duplicated().sum())
print("Duplicate order IDs:", orders["order_id"].duplicated().sum())
print("Duplicate delivery IDs:", deliveries["delivery_id"].duplicated().sum())
print("Duplicate campaign record IDs:", marketing["campaign_record_id"].duplicated().sum())

Duplicate customer IDs: 14
Duplicate order IDs: 12
Duplicate delivery IDs: 8
Duplicate campaign record IDs: 10

In [14]:
#ceck whether every order belongs to customer 
invalid_order_customers = orders[
    ~orders["customer_id"].isin(customers["customer_id"])
]

print("Orders with invalid customer IDs:", len(invalid_order_customers))

Orders with invalid customer IDs: 0

In [15]:
# every delivery belongs to order 
invalid_deliveries = deliveries[
    ~deliveries["order_id"].isin(orders["order_id"])
]

print("Deliveries with invalid order IDs:", len(invalid_deliveries))

Deliveries with invalid order IDs: 0

In [16]:
#check marketing customers 
invalid_marketing_customers = marketing[
    ~marketing["customer_id"].isin(customers["customer_id"])
]

print("Marketing records with invalid customer IDs:",
      len(invalid_marketing_customers))

Marketing records with invalid customer IDs: 0

In [17]:
# check campaign ID 
order_campaigns = set(orders["campaign_id"].dropna().unique())
marketing_campaigns = set(marketing["campaign_id"].dropna().unique())

invalid_order_campaigns = orders[
    orders["campaign_id"].notna() &
    ~orders["campaign_id"].isin(marketing_campaigns)
]

print("Orders with campaign IDs not found in Marketing:",
      len(invalid_order_campaigns))

Orders with campaign IDs not found in Marketing: 0

In [18]:
# check data columns 
date_columns = {
    "customers": ["signup_date"],
    "orders": ["order_date"],
    "deliveries": [
        "ship_date",
        "promised_delivery_date",
        "actual_delivery_date"
    ],
    "marketing": ["sent_date"]
}

for dataset_name, columns in date_columns.items():
    df = globals()[dataset_name]
    
    print(f"\n=== {dataset_name.upper()} ===")
    
    for col in columns:
        print(col, "→", df[col].dtype)

=== CUSTOMERS ===
signup_date → datetime64[us]

=== ORDERS ===
order_date → datetime64[us]

=== DELIVERIES ===
ship_date → datetime64[us]
promised_delivery_date → datetime64[us]
actual_delivery_date → datetime64[us]

=== MARKETING ===
sent_date → datetime64[us]

In [20]:
# check order status 
print(orders["order_status"].value_counts(dropna=False))
print(deliveries["delivery_status"].value_counts(dropna=False))
print(orders["payment_method"].value_counts(dropna=False))

order_status
Delivered     11859
Cancelled       613
Returned        493
Shipped         112
DELIVERED        60
delivered        60
Processing       16
RETURNED          4
cancelled         3
CANCELLED         3
returned          1
shipped           1
Name: count, dtype: int64
delivery_status
Delivered       12473
In Transit        113
Failed - RTO       88
Name: count, dtype: int64
payment_method
UPI                 4745
COD                 2847
Credit Card         2288
Debit Card          1667
Net Banking          824
Wallet               523
upi                  126
CC                    74
Cash on Delivery      67
debit card            38
Net banking           17
wallet                 9
Name: count, dtype: int64

In [ ]:
# clean the data

In [21]:
customers_clean = customers.copy()
orders_clean = orders.copy()
deliveries_clean = deliveries.copy()
marketing_clean = marketing.copy()

In [22]:
#convert dates 
customers_clean["signup_date"] = pd.to_datetime(
    customers_clean["signup_date"], errors="coerce"
)

orders_clean["order_date"] = pd.to_datetime(
    orders_clean["order_date"], errors="coerce"
)

deliveries_clean["ship_date"] = pd.to_datetime(
    deliveries_clean["ship_date"], errors="coerce"
)

deliveries_clean["promised_delivery_date"] = pd.to_datetime(
    deliveries_clean["promised_delivery_date"], errors="coerce"
)

deliveries_clean["actual_delivery_date"] = pd.to_datetime(
    deliveries_clean["actual_delivery_date"], errors="coerce"
)

marketing_clean["sent_date"] = pd.to_datetime(
    marketing_clean["sent_date"], errors="coerce"
)

In [24]:
# check the dates 
print("Customers signup dates:",
      customers_clean["signup_date"].isna().sum())

print("Orders dates:",
      orders_clean["order_date"].isna().sum())

print("Ship dates:",
      deliveries_clean["ship_date"].isna().sum())

print("Promised delivery dates:",
      deliveries_clean["promised_delivery_date"].isna().sum())

print("Actual delivery dates:",
      deliveries_clean["actual_delivery_date"].isna().sum())

print("Marketing dates:",
      marketing_clean["sent_date"].isna().sum())

Customers signup dates: 0
Orders dates: 0
Ship dates: 0
Promised delivery dates: 0
Actual delivery dates: 276
Marketing dates: 0

In [26]:
    
deliveries_clean[
    deliveries_clean["actual_delivery_date"].isna()
]["delivery_status"].value_counts(dropna=False)

delivery_status
In Transit      113
Failed - RTO     88
Delivered        75
Name: count, dtype: int64

In [27]:
missing_delivery_date = deliveries_clean[
    deliveries_clean["actual_delivery_date"].isna()
]

missing_orders = orders_clean[
    orders_clean["order_id"].isin(missing_delivery_date["order_id"])
]

print(missing_orders["order_status"].value_counts(dropna=False))

order_status
Shipped      112
Cancelled     88
Delivered     72
Returned       3
shipped        1
Name: count, dtype: int64

In [28]:
display(
    deliveries_clean[
        deliveries_clean["actual_delivery_date"].isna()
    ].head(10)
)

,delivery_id,order_id,courier_partner,delivery_zone,ship_date,promised_delivery_date,actual_delivery_date,delivery_status,delivery_attempts,courier_charge,delivery_rating
35,DLV000036,ORD000038,QuickCourier,Tier-2,2023-02-12,2023-02-17,NaT,Failed - RTO,3,45.7,NaN
64,DLV000065,ORD000067,SwiftShip,Metro,2023-02-28,2023-03-03,NaT,Failed - RTO,3,34.2,NaN
132,DLV000133,ORD000135,EasyDeliver,Tier-3,2023-04-04,2023-04-10,NaT,Failed - RTO,3,77.3,NaN
208,DLV000209,ORD000216,EasyDeliver,Tier-3,2023-05-09,2023-05-13,NaT,Failed - RTO,3,70.0,NaN
406,DLV000407,ORD000424,EasyDeliver,Tier-3,2023-07-04,2023-07-08,NaT,Delivered,1,68.9,NaN
490,DLV000491,ORD000514,EasyDeliver,Tier-3,2023-07-23,2023-07-28,NaT,Delivered,1,76.0,NaN
579,DLV000580,ORD000606,QuickCourier,Metro,2023-08-09,2023-08-12,NaT,Failed - RTO,3,36.7,NaN
664,DLV000665,ORD000688,RoadRunner Logistics,Metro,2023-08-27,2023-08-29,NaT,Failed - RTO,3,28.4,NaN
805,DLV000806,ORD000848,EasyDeliver,Tier-3,2023-09-17,2023-09-21,NaT,Delivered,2,77.4,1.0
837,DLV000838,ORD000881,EasyDeliver,Metro,2023-09-22,2023-09-25,NaT,Failed - RTO,3,38.2,NaN

In [29]:
#remove duplicate rows
customers_clean = customers_clean.drop_duplicates()
orders_clean = orders_clean.drop_duplicates()
deliveries_clean = deliveries_clean.drop_duplicates()
marketing_clean = marketing_clean.drop_duplicates()

In [30]:
print("Customers:", customers_clean.shape)
print("Orders:", orders_clean.shape)
print("Deliveries:", deliveries_clean.shape)
print("Marketing:", marketing_clean.shape)

Customers: (1850, 14)
Orders: (13213, 14)
Deliveries: (12666, 11)
Marketing: (3890, 14)

In [31]:
# create delivery delay 
deliveries_clean["delivery_delay_days"] = (
    deliveries_clean["actual_delivery_date"]
    - deliveries_clean["promised_delivery_date"]
).dt.days

In [32]:
display(
    deliveries_clean[
        [
            "order_id",
            "promised_delivery_date",
            "actual_delivery_date",
            "delivery_delay_days",
            "delivery_status"
        ]
    ].head(10)
)

,order_id,promised_delivery_date,actual_delivery_date,delivery_delay_days,delivery_status
0,ORD000001,2023-01-03,2023-01-03,0.0,Delivered
1,ORD000002,2023-01-10,2023-01-10,0.0,Delivered
2,ORD000003,2023-01-12,2023-01-12,0.0,Delivered
3,ORD000004,2023-01-18,2023-01-18,0.0,Delivered
4,ORD000005,2023-01-16,2023-01-15,-1.0,Delivered
5,ORD000006,2023-01-17,2023-01-16,-1.0,Delivered
6,ORD000007,2023-01-19,2023-01-19,0.0,Delivered
7,ORD000008,2023-01-24,2023-01-23,-1.0,Delivered
8,ORD000009,2023-01-23,2023-01-23,0.0,Delivered
9,ORD000010,2023-01-23,2023-01-24,1.0,Delivered

In [33]:
#create delayed flag 
deliveries_clean["is_delayed"] = (
    deliveries_clean["delivery_delay_days"] > 0
).astype(int)

In [34]:
# check order values 
print("Negative quantity:",
      (orders_clean["quantity"] < 0).sum())

print("Negative unit price:",
      (orders_clean["unit_price"] < 0).sum())

print("Negative order value:",
      (orders_clean["order_value"] < 0).sum())

print("Negative shipping fee:",
      (orders_clean["shipping_fee"] < 0).sum())

print("Discount below 0:",
      (orders_clean["discount_pct"] < 0).sum())

print("Discount above 100:",
      (orders_clean["discount_pct"] > 100).sum())

Negative quantity: 0
Negative unit price: 0
Negative order value: 0
Negative shipping fee: 0
Discount below 0: 0
Discount above 100: 0

In [35]:
# create new revenue 
orders_clean["net_revenue"] = (
    orders_clean["order_value"] + orders_clean["shipping_fee"]
)

In [36]:
# identity valid purchases 
print(orders_clean["order_status"].value_counts())

order_status
Delivered     11847
Cancelled       613
Returned        493
Shipped         112
DELIVERED        60
delivered        60
Processing       16
RETURNED          4
cancelled         3
CANCELLED         3
returned          1
shipped           1
Name: count, dtype: int64

In [38]:
orders_clean["is_valid_purchase"] = (
    orders_clean["order_status"] == "Delivered"
).astype(int)

In [39]:
print(orders_clean["order_status"].value_counts(dropna=False))

order_status
Delivered     11847
Cancelled       613
Returned        493
Shipped         112
DELIVERED        60
delivered        60
Processing       16
RETURNED          4
cancelled         3
CANCELLED         3
returned          1
shipped           1
Name: count, dtype: int64

In [40]:
orders_clean["is_valid_purchase"] = (
    orders_clean["order_status"] == "Delivered"
).astype(int)

In [41]:
print(orders_clean["is_valid_purchase"].value_counts())

is_valid_purchase
1    11847
0     1366
Name: count, dtype: int64

In [42]:
valid_orders = orders_clean[
    orders_clean["is_valid_purchase"] == 1
].copy()

print("Total orders:", len(orders_clean))
print("Valid purchases:", len(valid_orders))

Total orders: 13213
Valid purchases: 11847

In [ ]:
# find analysis date

In [43]:
#valid purchase date in the dataset
analysis_date = valid_orders["order_date"].max()

print("Analysis date:", analysis_date)

Analysis date: 2025-12-29 00:00:00

In [44]:
#calculate how long each customer will inactive 
customer_last_purchase = (
    valid_orders
    .groupby("customer_id")["order_date"]
    .max()
    .reset_index()
)

customer_last_purchase.columns = [
    "customer_id",
    "last_purchase_date"
]

customer_last_purchase["days_since_last_purchase"] = (
    analysis_date - customer_last_purchase["last_purchase_date"]
).dt.days

display(customer_last_purchase.head())

  customer_id last_purchase_date  days_since_last_purchase
0       C0001         2024-11-16                       408
1       C0002         2024-03-16                       653
2       C0003         2025-05-31                       212
3       C0004         2024-02-24                       674
4       C0005         2025-10-11                        79

In [45]:
# add churn status
customer_last_purchase["churn_status"] = np.where(
    customer_last_purchase["days_since_last_purchase"] > 90,
    "Churned",
    "Active"
)

display(customer_last_purchase.head(10))

  customer_id last_purchase_date  days_since_last_purchase churn_status
0       C0001         2024-11-16                       408      Churned
1       C0002         2024-03-16                       653      Churned
2       C0003         2025-05-31                       212      Churned
3       C0004         2024-02-24                       674      Churned
4       C0005         2025-10-11                        79       Active
5       C0006         2023-10-21                       800      Churned
6       C0007         2024-03-31                       638      Churned
7       C0008         2023-09-23                       828      Churned
8       C0009         2025-01-24                       339      Churned
9       C0010         2023-01-18                      1076      Churned

In [46]:
#calculate churn numbers
churn_summary = customer_last_purchase["churn_status"].value_counts()

print(churn_summary)

churn_status
Active     869
Churned    799
Name: count, dtype: int64

In [47]:
total_customers_with_purchase = len(customer_last_purchase)

churned_customers = (
    customer_last_purchase["churn_status"] == "Churned"
).sum()

active_customers = (
    customer_last_purchase["churn_status"] == "Active"
).sum()

churn_rate = (
    churned_customers / total_customers_with_purchase
) * 100

print("Customers with at least one purchase:", total_customers_with_purchase)
print("Churned customers:", churned_customers)
print("Active customers:", active_customers)
print("Churn rate:", round(churn_rate, 2), "%")

Customers with at least one purchase: 1668
Churned customers: 799
Active customers: 869
Churn rate: 47.9 %

In [48]:
#check customers who never purchased 
customers_without_purchase = customers_clean[
    ~customers_clean["customer_id"].isin(
        customer_last_purchase["customer_id"]
    )
]

print("Total customers:", len(customers_clean))
print("Customers with purchases:", len(customer_last_purchase))
print("Customers without purchases:", len(customers_without_purchase))

Total customers: 1850
Customers with purchases: 1668
Customers without purchases: 182

In [ ]:
#build customer master table

In [49]:
#all customers
customer_master = customers_clean.copy()

print("Customer master shape:", customer_master.shape)

Customer master shape: (1850, 14)

In [50]:
#add purchase inf
customer_order_metrics = (
    valid_orders
    .groupby("customer_id")
    .agg(
        total_orders=("order_id", "nunique"),
        total_quantity=("quantity", "sum"),
        total_revenue=("net_revenue", "sum"),
        average_order_value=("net_revenue", "mean"),
        first_purchase_date=("order_date", "min"),
        last_purchase_date=("order_date", "max")
    )
    .reset_index()
)

display(customer_order_metrics.head())

,customer_id,total_orders,total_quantity,total_revenue,average_order_value,first_purchase_date,last_purchase_date
0,C0001,8,18,19605.00,2450.625000,2023-01-01,2024-11-16
1,C0002,16,26,17138.65,1071.165625,2023-01-12,2024-03-16
2,C0003,18,27,51265.75,2848.097222,2023-01-12,2025-05-31
3,C0004,12,30,14641.95,1220.162500,2023-01-16,2024-02-24
4,C0005,25,37,53772.05,2150.882000,2023-01-22,2025-10-11

In [51]:
#merge into customer master 
customer_master = customer_master.merge(
    customer_order_metrics,
    on="customer_id",
    how="left"
)

print(customer_master.shape)
display(customer_master.head())

(1850, 20)

,customer_id,customer_name,gender,age,email,city,state,region,city_tier,signup_date,acquisition_channel,email_opt_in,loyalty_member,preferred_device,total_orders,total_quantity,total_revenue,average_order_value,first_purchase_date,last_purchase_date
0,C0001,Shweta Mishra,Female,38.0,shweta.mishra100@example.com,Bengaluru,Karnataka,South,Metro,2023-01-01,Paid Ads,Yes,No,Android,8.0,18.0,19605.00,2450.625000,2023-01-01,2024-11-16
1,C0002,Sneha Ali,Female,24.0,sneha.ali101@example.com,Bhopal,Madhya Pradesh,Central,Tier-2,2023-01-01,Social Media,Yes,Yes,iOS,16.0,26.0,17138.65,1071.165625,2023-01-12,2024-03-16
2,C0003,Akash Trivedi,Male,35.0,akash.trivedi102@example.com,Lucknow,Uttar Pradesh,North,Tier-2,2023-01-01,Organic Search,Yes,No,Android,18.0,27.0,51265.75,2848.097222,2023-01-12,2025-05-31
3,C0004,Radhika Pandey,Female,30.0,radhika.pandey103@example.com,Udaipur,Rajasthan,North,Tier-3,2023-01-02,Organic Search,No,No,Android,12.0,30.0,14641.95,1220.162500,2023-01-16,2024-02-24
4,C0005,Bhavna Sethi,Female,22.0,bhavna.sethi104@example.com,Udaipur,Rajasthan,North,Tier-3,2023-01-03,Organic Search,No,Yes,Android,25.0,37.0,53772.05,2150.882000,2023-01-22,2025-10-11

In [52]:
# add churn inf
customer_master = customer_master.merge(
    customer_last_purchase[
        [
            "customer_id",
            "days_since_last_purchase",
            "churn_status"
        ]
    ],
    on="customer_id",
    how="left"
)

In [53]:
display(
    customer_master[
        [
            "customer_id",
            "total_orders",
            "total_revenue",
            "average_order_value",
            "last_purchase_date",
            "days_since_last_purchase",
            "churn_status"
        ]
    ].head(10)
)

,customer_id,total_orders,total_revenue,average_order_value,last_purchase_date,days_since_last_purchase,churn_status
0,C0001,8.0,19605.00,2450.625000,2024-11-16,408.0,Churned
1,C0002,16.0,17138.65,1071.165625,2024-03-16,653.0,Churned
2,C0003,18.0,51265.75,2848.097222,2025-05-31,212.0,Churned
3,C0004,12.0,14641.95,1220.162500,2024-02-24,674.0,Churned
4,C0005,25.0,53772.05,2150.882000,2025-10-11,79.0,Active
5,C0006,5.0,8135.00,1627.000000,2023-10-21,800.0,Churned
6,C0007,6.0,9878.60,1646.433333,2024-03-31,638.0,Churned
7,C0008,4.0,3599.10,899.775000,2023-09-23,828.0,Churned
8,C0009,13.0,21388.20,1645.246154,2025-01-24,339.0,Churned
9,C0010,1.0,1769.00,1769.000000,2023-01-18,1076.0,Churned

In [54]:
# correct customers who never purchased 
customer_master["customer_status"] = np.where(
    customer_master["total_orders"].isna(),
    "Never Purchased",
    customer_master["churn_status"]
)

In [55]:
print(customer_master["customer_status"].value_counts(dropna=False))

customer_status
Active             869
Churned            799
Never Purchased    182
Name: count, dtype: int64

In [56]:
#fill purchase matrics for never-purchased customers 
purchase_columns = [
    "total_orders",
    "total_quantity",
    "total_revenue",
    "average_order_value"
]

customer_master[purchase_columns] = (
    customer_master[purchase_columns].fillna(0)
)

In [57]:
display(
    customer_master[
        [
            "customer_id",
            "total_orders",
            "total_revenue",
            "average_order_value",
            "customer_status"
        ]
    ].head(10)
)

,customer_id,total_orders,total_revenue,average_order_value,customer_status
0,C0001,8.0,19605.00,2450.625000,Churned
1,C0002,16.0,17138.65,1071.165625,Churned
2,C0003,18.0,51265.75,2848.097222,Churned
3,C0004,12.0,14641.95,1220.162500,Churned
4,C0005,25.0,53772.05,2150.882000,Active
5,C0006,5.0,8135.00,1627.000000,Churned
6,C0007,6.0,9878.60,1646.433333,Churned
7,C0008,4.0,3599.10,899.775000,Churned
8,C0009,13.0,21388.20,1645.246154,Churned
9,C0010,1.0,1769.00,1769.000000,Churned

In [ ]:
#add delivery behaviour

In [58]:
#connect deliveries to customers
order_customer = valid_orders[
    ["order_id", "customer_id"]
].drop_duplicates()

valid_deliveries = deliveries_clean.merge(
    order_customer,
    on="order_id",
    how="inner"
)

print("Valid delivery records:", valid_deliveries.shape)
valid_deliveries.head()

Valid delivery records: (11847, 14)

,delivery_id,order_id,courier_partner,delivery_zone,ship_date,promised_delivery_date,actual_delivery_date,delivery_status,delivery_attempts,courier_charge,delivery_rating,delivery_delay_days,is_delayed,customer_id
0,DLV000001,ORD000001,SwiftShip,Metro,2023-01-01,2023-01-03,2023-01-03,Delivered,1,44.9,NaN,0.0,0,C0001
1,DLV000002,ORD000002,QuickCourier,Tier-2,2023-01-07,2023-01-10,2023-01-10,Delivered,1,51.0,5.0,0.0,0,C0009
2,DLV000004,ORD000004,RoadRunner Logistics,Tier-3,2023-01-12,2023-01-18,2023-01-18,Delivered,1,68.3,NaN,0.0,0,C0008
3,DLV000005,ORD000005,QuickCourier,Tier-2,2023-01-12,2023-01-16,2023-01-15,Delivered,1,50.5,NaN,-1.0,0,C0002
4,DLV000006,ORD000006,SwiftShip,Tier-2,2023-01-14,2023-01-17,2023-01-16,Delivered,1,59.7,NaN,-1.0,0,C0003

In [59]:
# create order level deleivery matrics 
delivery_order_metrics = (
    valid_deliveries
    .groupby(["customer_id", "order_id"])
    .agg(
        delivery_delay_days=("delivery_delay_days", "max"),
        is_delayed=("is_delayed", "max"),
        delivery_rating=("delivery_rating", "mean"),
        delivery_attempts=("delivery_attempts", "max")
    )
    .reset_index()
)

delivery_order_metrics.head()

,customer_id,order_id,delivery_delay_days,is_delayed,delivery_rating,delivery_attempts
0,C0001,ORD000001,0.0,0,NaN,1
1,C0001,ORD000425,0.0,0,4.0,1
2,C0001,ORD000700,0.0,0,NaN,1
3,C0001,ORD001092,0.0,0,NaN,1
4,C0001,ORD003732,0.0,0,NaN,1

In [60]:
# create customer level delivery matrics 
delivery_metrics = (
    delivery_order_metrics
    .groupby("customer_id")
    .agg(
        total_deliveries=("order_id", "nunique"),
        delayed_deliveries=("is_delayed", "sum"),
        avg_delivery_delay_days=("delivery_delay_days", "mean"),
        avg_delivery_rating=("delivery_rating", "mean"),
        avg_delivery_attempts=("delivery_attempts", "mean")
    )
    .reset_index()
)

delivery_metrics["delivery_delay_rate"] = (
    delivery_metrics["delayed_deliveries"]
    / delivery_metrics["total_deliveries"]
    * 100
)

delivery_metrics.head()

,customer_id,total_deliveries,delayed_deliveries,avg_delivery_delay_days,avg_delivery_rating,avg_delivery_attempts,delivery_delay_rate
0,C0001,8,0,-0.125000,4.000,1.000000,0.000000
1,C0002,16,3,0.062500,3.875,1.062500,18.750000
2,C0003,18,5,0.888889,3.900,1.111111,27.777778
3,C0004,12,5,1.166667,2.000,1.250000,41.666667
4,C0005,25,5,0.160000,4.000,1.040000,20.000000

In [61]:
# merge to customer master 
customer_master = customer_master.merge(
    delivery_metrics,
    on="customer_id",
    how="left"
)

In [62]:
delivery_columns = [
    "total_deliveries",
    "delayed_deliveries",
    "delivery_delay_rate",
    "avg_delivery_delay_days",
    "avg_delivery_rating",
    "avg_delivery_attempts"
]

customer_master[delivery_columns] = (
    customer_master[delivery_columns].fillna(0)
)

In [63]:
#check wheather delivery delays are associated with churn 
delivery_churn_analysis = (
    customer_master
    .groupby("customer_status")
    .agg(
        customers=("customer_id", "nunique"),
        avg_delay_rate=("delivery_delay_rate", "mean"),
        avg_delay_days=("avg_delivery_delay_days", "mean"),
        avg_delivery_rating=("avg_delivery_rating", "mean")
    )
    .reset_index()
)

delivery_churn_analysis

,customer_status,customers,avg_delay_rate,avg_delay_days,avg_delivery_rating
0,Active,869,25.719622,0.467127,3.554520
1,Churned,799,26.678151,0.574948,3.200799
2,Never Purchased,182,0.000000,0.000000,0.000000

In [ ]:
#marketing behaviour

In [64]:
marketing_clean.head()

,campaign_record_id,campaign_id,campaign_name,campaign_type,channel,customer_id,sent_date,discount_offered_pct,cost_per_send,opened,clicked,converted,conversion_order_id,unsubscribed
0,CR000001,CMP001,Welcome Series,Welcome,SMS,C0003,2023-01-01,10,0.18,No,No,No,NaN,No
1,CR000002,CMP001,Welcome Series,Welcome,Push Notification,C0004,2023-01-02,10,0.05,No,No,No,NaN,No
2,CR000003,CMP001,Welcome Series,Welcome,Email,C0001,2023-01-03,10,NaN,Yes,No,No,NaN,No
3,CR000004,CMP001,Welcome Series,Welcome,Email,C0006,2023-01-03,10,0.25,Yes,Yes,No,NaN,No
4,CR000005,CMP001,Welcome Series,Welcome,WhatsApp,C0005,2023-01-05,10,0.80,Yes,Yes,No,NaN,No

In [65]:
marketing_clean.info()

<class 'pandas.DataFrame'>
Index: 3890 entries, 0 to 3899
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   campaign_record_id    3890 non-null   str
 1   campaign_id           3890 non-null   str
 2   campaign_name         3890 non-null   str
 3   campaign_type         3890 non-null   str
 4   channel               3832 non-null   str
 5   customer_id           3890 non-null   str
 6   sent_date             3890 non-null   datetime64[us]
 7   discount_offered_pct  3890 non-null   int64
 8   cost_per_send         3812 non-null   float64
 9   opened                3890 non-null   str
 10  clicked               3890 non-null   str
 11  converted             3890 non-null   str
 12  conversion_order_id   103 non-null    str
 13  unsubscribed          3890 non-null   str
dtypes: datetime64[us](1), float64(1), int64(1), str(11)
memory usage: 707.9 KB

In [66]:
marketing_clean[[
    "opened",
    "clicked",
    "converted",
    "unsubscribed"
]].apply(lambda x: x.value_counts(dropna=False))

     opened  clicked  converted  unsubscribed
N        17      NaN        NaN           NaN
No     2337   3504.0     3787.0        3881.0
Y        22      NaN        NaN           NaN
Yes    1514    386.0      103.0           9.0

In [67]:
#convert campaign resources to 0/1
marketing_clean["opened_flag"] = (
    marketing_clean["opened"] == "Yes"
).astype(int)

marketing_clean["clicked_flag"] = (
    marketing_clean["clicked"] == "Yes"
).astype(int)

marketing_clean["converted_flag"] = (
    marketing_clean["converted"] == "Yes"
).astype(int)

marketing_clean["unsubscribed_flag"] = (
    marketing_clean["unsubscribed"] == "Yes"
).astype(int)

In [68]:
marketing_clean[
    [
        "opened",
        "opened_flag",
        "clicked",
        "clicked_flag",
        "converted",
        "converted_flag",
        "unsubscribed",
        "unsubscribed_flag"
    ]
].head()

,opened,opened_flag,clicked,clicked_flag,converted,converted_flag,unsubscribed,unsubscribed_flag
0,No,0,No,0,No,0,No,0
1,No,0,No,0,No,0,No,0
2,Yes,1,No,0,No,0,No,0
3,Yes,1,Yes,1,No,0,No,0
4,Yes,1,Yes,1,No,0,No,0

In [69]:
#create customer level marketing matrics 
marketing_metrics = (
    marketing_clean
    .groupby("customer_id")
    .agg(
        campaigns_received=("campaign_record_id", "nunique"),
        campaigns_opened=("opened_flag", "sum"),
        campaigns_clicked=("clicked_flag", "sum"),
        campaigns_converted=("converted_flag", "sum"),
        campaigns_unsubscribed=("unsubscribed_flag", "sum"),
        total_marketing_cost=("cost_per_send", "sum"),
        avg_discount_offered=("discount_offered_pct", "mean")
    )
    .reset_index()
)

In [70]:
#calculate engagement rates
marketing_metrics["open_rate"] = (
    marketing_metrics["campaigns_opened"]
    / marketing_metrics["campaigns_received"]
    * 100
)

marketing_metrics["click_rate"] = (
    marketing_metrics["campaigns_clicked"]
    / marketing_metrics["campaigns_received"]
    * 100
)

marketing_metrics["conversion_rate"] = (
    marketing_metrics["campaigns_converted"]
    / marketing_metrics["campaigns_received"]
    * 100
)

marketing_metrics["unsubscribe_rate"] = (
    marketing_metrics["campaigns_unsubscribed"]
    / marketing_metrics["campaigns_received"]
    * 100
)

marketing_metrics.head()

,customer_id,campaigns_received,campaigns_opened,campaigns_clicked,campaigns_converted,campaigns_unsubscribed,total_marketing_cost,avg_discount_offered,open_rate,click_rate,conversion_rate,unsubscribe_rate
0,C0001,1,1,0,0,0,0.00,10.00,100.000000,0.0,0.0,0.0
1,C0002,3,1,0,0,0,1.03,15.00,33.333333,0.0,0.0,0.0
2,C0003,4,2,1,1,0,1.28,13.75,50.000000,25.0,25.0,0.0
3,C0004,5,2,2,0,0,1.83,19.00,40.000000,40.0,0.0,0.0
4,C0005,4,2,2,0,0,1.21,15.00,50.000000,50.0,0.0,0.0

In [71]:
#adding marketing data to customer master 
customer_master = customer_master.merge(
    marketing_metrics,
    on="customer_id",
    how="left"
)

In [72]:
marketing_columns = [
    "campaigns_received",
    "campaigns_opened",
    "campaigns_clicked",
    "campaigns_converted",
    "campaigns_unsubscribed",
    "total_marketing_cost",
    "avg_discount_offered",
    "open_rate",
    "click_rate",
    "conversion_rate",
    "unsubscribe_rate"
]

customer_master[marketing_columns] = (
    customer_master[marketing_columns].fillna(0)
)

In [73]:
#compare marketing engagemnet with churn
marketing_churn_analysis = (
    customer_master
    .groupby("customer_status")
    .agg(
        customers=("customer_id", "nunique"),
        avg_campaigns_received=("campaigns_received", "mean"),
        avg_open_rate=("open_rate", "mean"),
        avg_click_rate=("click_rate", "mean"),
        avg_conversion_rate=("conversion_rate", "mean"),
        avg_discount=("avg_discount_offered", "mean"),
        avg_unsubscribe_rate=("unsubscribe_rate", "mean")
    )
    .reset_index()
)

marketing_churn_analysis

,customer_status,customers,avg_campaigns_received,avg_open_rate,avg_click_rate,avg_conversion_rate,avg_discount,avg_unsubscribe_rate
0,Active,869,1.773303,39.949586,9.766289,2.947011,11.421763,0.345224
1,Churned,799,2.556946,38.687280,9.696360,2.848257,13.143612,0.348352
2,Never Purchased,182,1.681319,40.082418,9.166667,0.183150,11.574176,0.000000

In [ ]:
#Repeat Purchase & Customer Loyalty

In [74]:
#create repeat purchase flag 
customer_master["is_repeat_customer"] = (
    customer_master["total_orders"] >= 2
).astype(int)

In [75]:
#create loyalty metrics 
loyalty_analysis = (
    customer_master[
        customer_master["total_orders"] > 0
    ]
    .agg(
        purchasing_customers=("customer_id", "nunique"),
        repeat_customers=("is_repeat_customer", "sum"),
        average_orders_per_customer=("total_orders", "mean"),
        average_revenue_per_customer=("total_revenue", "mean")
    )
)

loyalty_analysis

,customer_id,is_repeat_customer,total_orders,total_revenue
purchasing_customers,1668.0,NaN,NaN,NaN
repeat_customers,NaN,1392.0,NaN,NaN
average_orders_per_customer,NaN,NaN,7.102518,NaN
average_revenue_per_customer,NaN,NaN,NaN,15265.715198

In [76]:
# calculate repeat purchas erate 
purchasing_customers = (
    customer_master["total_orders"] > 0
).sum()

repeat_customers = (
    customer_master["is_repeat_customer"] == 1
).sum()

repeat_purchase_rate = (
    repeat_customers / purchasing_customers * 100
)

print("Repeat Purchase Rate:", round(repeat_purchase_rate, 2), "%")

Repeat Purchase Rate: 83.45 %

In [77]:
#comapre repaeat behaviour with churn 
repeat_churn_analysis = (
    customer_master[
        customer_master["total_orders"] > 0
    ]
    .groupby("customer_status")
    .agg(
        customers=("customer_id", "nunique"),
        avg_orders=("total_orders", "mean"),
        avg_revenue=("total_revenue", "mean"),
        repeat_customer_rate=("is_repeat_customer", "mean")
    )
    .reset_index()
)

repeat_churn_analysis["repeat_customer_rate"] = (
    repeat_churn_analysis["repeat_customer_rate"] * 100
)

repeat_churn_analysis

  customer_status  customers  avg_orders   avg_revenue  repeat_customer_rate
0          Active        869    8.744534  18706.426697             91.599540
1         Churned        799    5.316646  11523.564643             74.593242

In [ ]:
#Customer Lifetime Value (CLV)

In [78]:
#create historical CLV
customer_master["historical_clv"] = (
    customer_master["total_revenue"]
)

In [79]:
customer_master[
    [
        "customer_id",
        "total_orders",
        "total_revenue",
        "historical_clv"
    ]
].head()

  customer_id  total_orders  total_revenue  historical_clv
0       C0001           8.0       19605.00        19605.00
1       C0002          16.0       17138.65        17138.65
2       C0003          18.0       51265.75        51265.75
3       C0004          12.0       14641.95        14641.95
4       C0005          25.0       53772.05        53772.05

In [82]:
# create clv segments 
purchasing_clv = customer_master.loc[
    customer_master["total_orders"] > 0,
    "historical_clv"
]

clv_25 = purchasing_clv.quantile(0.25)
clv_75 = purchasing_clv.quantile(0.75)

customer_master["clv_segment"] = np.select(
    [
        customer_master["historical_clv"] <= clv_25,
        customer_master["historical_clv"] <= clv_75
    ],
    [
        "Low Value",
        "Medium Value"
    ],
    default="High Value"
)

customer_master.loc[
    customer_master["total_orders"] == 0,
    "clv_segment"
] = "No Purchase"

In [83]:
#check distribution 
customer_master["clv_segment"].value_counts()

clv_segment
Medium Value    834
High Value      417
Low Value       417
No Purchase     182
Name: count, dtype: int64

In [84]:
#compare clv with churn 
clv_churn_analysis = (
    customer_master[
        customer_master["total_orders"] > 0
    ]
    .groupby("customer_status")
    .agg(
        customers=("customer_id", "nunique"),
        average_clv=("historical_clv", "mean"),
        median_clv=("historical_clv", "median"),
        total_customer_value=("historical_clv", "sum")
    )
    .reset_index()
)

clv_churn_analysis

  customer_status  customers   average_clv  median_clv  total_customer_value
0          Active        869  18706.426697     11649.6           16255884.80
1         Churned        799  11523.564643      5991.2            9207328.15

In [85]:
#compare high valued churnd customers
high_value_churned = customer_master[
    (customer_master["customer_status"] == "Churned") &
    (customer_master["clv_segment"] == "High Value")
].sort_values(
    "historical_clv",
    ascending=False
)

high_value_churned[
    [
        "customer_id",
        "customer_name",
        "total_orders",
        "historical_clv",
        "days_since_last_purchase",
        "delivery_delay_rate",
        "open_rate",
        "clv_segment"
    ]
].head(10)

,customer_id,customer_name,total_orders,historical_clv,days_since_last_purchase,delivery_delay_rate,open_rate,clv_segment
395,C0396,Sanjay Kumar,20.0,127874.35,99.0,10.000000,50.000000,High Value
179,C0180,Dev Gill,16.0,124854.45,249.0,31.250000,100.000000,High Value
326,C0327,Pranav Mehta,11.0,117394.80,325.0,54.545455,33.333333,High Value
1216,C1217,Vikram Sethi,8.0,99275.00,158.0,12.500000,100.000000,High Value
455,C0456,Vandana Kumar,15.0,78642.15,160.0,40.000000,50.000000,High Value
13,C0014,Nikhil Jadhav,20.0,72563.55,207.0,25.000000,100.000000,High Value
150,C0151,Ajay Kaur,21.0,72283.55,419.0,28.571429,50.000000,High Value
309,C0310,Anil Yadav,25.0,70949.90,177.0,4.000000,25.000000,High Value
708,C0709,Sunil Kapoor,1.0,70698.00,611.0,0.000000,66.666667,High Value
577,C0578,Harsh Gupta,31.0,69508.55,151.0,32.258065,50.000000,High Value

In [ ]:
#cohort Retention Analysis

In [86]:
#create first purchase 
customer_master["first_purchase_month"] = (
    customer_master["first_purchase_date"]
    .dt.to_period("M")
)

In [87]:
customer_master[
    ["customer_id", "first_purchase_date", "first_purchase_month"]
].head()

  customer_id first_purchase_date first_purchase_month
0       C0001          2023-01-01              2023-01
1       C0002          2023-01-12              2023-01
2       C0003          2023-01-12              2023-01
3       C0004          2023-01-16              2023-01
4       C0005          2023-01-22              2023-01

In [88]:
#add purchase month to valid orders
valid_orders["purchase_month"] = (
    valid_orders["order_date"]
    .dt.to_period("M")
)

In [89]:
#attach each custom to their orders
valid_orders_cohort = valid_orders.merge(
    customer_master[
        ["customer_id", "first_purchase_month"]
    ],
    on="customer_id",
    how="left"
)

In [91]:
#calculate months since first purchase 
valid_orders_cohort["months_since_first_purchase"] = (
    valid_orders_cohort["purchase_month"]
    - valid_orders_cohort["first_purchase_month"]
).apply(lambda x: x.n)

In [92]:
#create chort customer counts 
cohort_retention = (
    valid_orders_cohort
    .groupby(
        [
            "first_purchase_month",
            "months_since_first_purchase"
        ]
    )["customer_id"]
    .nunique()
    .reset_index()
)

cohort_retention.head(10)

  first_purchase_month  months_since_first_purchase  customer_id
0              2023-01                            0           23
1              2023-01                            1            9
2              2023-01                            2            9
3              2023-01                            3            7
4              2023-01                            4           10
5              2023-01                            5            5
6              2023-01                            6           10
7              2023-01                            7            9
8              2023-01                            8            5
9              2023-01                            9            9

In [93]:
# size
cohort_sizes = (
    customer_master[
        customer_master["total_orders"] > 0
    ]
    .groupby("first_purchase_month")["customer_id"]
    .nunique()
    .reset_index()
)

cohort_sizes.columns = [
    "first_purchase_month",
    "cohort_size"
]

In [94]:
#calculate retention percentage 
cohort_retention = cohort_retention.merge(
    cohort_sizes,
    on="first_purchase_month",
    how="left"
)

cohort_retention["retention_rate"] = (
    cohort_retention["customer_id"]
    / cohort_retention["cohort_size"]
    * 100
)

In [95]:
cohort_retention.head(15)

,first_purchase_month,months_since_first_purchase,customer_id,cohort_size,retention_rate
0,2023-01,0,23,23,100.000000
1,2023-01,1,9,23,39.130435
2,2023-01,2,9,23,39.130435
3,2023-01,3,7,23,30.434783
4,2023-01,4,10,23,43.478261
5,2023-01,5,5,23,21.739130
6,2023-01,6,10,23,43.478261
7,2023-01,7,9,23,39.130435
8,2023-01,8,5,23,21.739130
9,2023-01,9,9,23,39.130435
10,2023-01,10,8,23,34.782609
11,2023-01,11,5,23,21.739130
12,2023-01,12,6,23,26.086957
13,2023-01,13,4,23,17.391304
14,2023-01,14,4,23,17.391304

In [96]:
#create retention matrix
retention_matrix = cohort_retention.pivot(
    index="first_purchase_month",
    columns="months_since_first_purchase",
    values="retention_rate"
)

retention_matrix

months_since_first_purchase,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
first_purchase_month,,,,,,,,,,,,,,,,,,,,,
2023-01,100.0,39.130435,39.130435,30.434783,43.478261,21.739130,43.478261,39.130435,21.739130,39.130435,...,26.086957,13.043478,8.695652,21.739130,17.391304,17.391304,4.347826,13.043478,21.739130,13.043478
2023-02,100.0,37.500000,37.500000,29.166667,33.333333,29.166667,25.000000,20.833333,29.166667,37.500000,...,4.166667,20.833333,12.500000,25.000000,20.833333,25.000000,20.833333,16.666667,8.333333,NaN
2023-03,100.0,22.222222,51.851852,37.037037,55.555556,29.629630,29.629630,37.037037,44.444444,33.333333,...,22.222222,14.814815,14.814815,33.333333,22.222222,18.518519,37.037037,25.925926,NaN,NaN
2023-04,100.0,13.888889,25.000000,22.222222,27.777778,11.111111,22.222222,30.555556,19.444444,22.222222,...,11.111111,2.777778,19.444444,19.444444,19.444444,25.000000,16.666667,NaN,NaN,NaN
2023-05,100.0,38.461538,38.461538,25.641026,41.025641,43.589744,35.897436,30.769231,23.076923,10.256410,...,17.948718,10.256410,7.692308,23.076923,20.512821,17.948718,NaN,NaN,NaN,NaN
2023-06,100.0,43.750000,21.875000,37.500000,31.250000,34.375000,40.625000,31.250000,31.250000,21.875000,...,15.625000,15.625000,25.000000,18.750000,12.500000,NaN,NaN,NaN,NaN,NaN
2023-07,100.0,44.186047,27.906977,44.186047,37.209302,34.883721,32.558140,25.581395,27.906977,20.930233,...,11.627907,9.302326,11.627907,9.302326,NaN,NaN,NaN,NaN,NaN,NaN
2023-08,100.0,47.169811,60.377358,58.490566,33.962264,43.396226,28.301887,22.641509,35.849057,39.622642,...,18.867925,24.528302,13.207547,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-09,100.0,54.000000,52.000000,36.000000,34.000000,36.000000,32.000000,24.000000,36.000000,32.000000,...,22.000000,14.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-10,100.0,55.102041,34.693878,42.857143,26.530612,36.734694,34.693878,36.734694,32.653061,34.693878,...,18.367347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-11,100.0,42.592593,35.185185,35.185185,37.037037,27.777778,18.518519,24.074074,22.222222,14.814815,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-12,100.0,42.857143,45.238095,33.333333,35.714286,26.190476,35.714286,38.095238,23.809524,30.952381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01,100.0,28.571429,40.000000,25.714286,48.571429,37.142857,37.142857,31.428571,31.428571,48.571429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-02,100.0,44.444444,42.222222,40.000000,40.000000,42.222222,26.666667,28.888889,31.111111,40.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-03,100.0,34.883721,30.232558,25.581395,30.232558,30.232558,13.953488,27.906977,23.255814,16.279070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-04,100.0,34.375000,34.375000,34.375000,34.375000,31.250000,43.750000,25.000000,31.250000,31.250000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05,100.0,28.000000,36.000000,30.000000,38.000000,40.000000,30.000000,34.000000,34.000000,16.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-06,100.0,35.000000,47.500000,45.000000,27.500000,52.500000,27.500000,30.000000,27.500000,17.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-07,100.0,35.294118,29.411765,45.098039,39.215686,31.372549,31.372549,15.686275,25.490196,21.568627,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-08,100.0,35.555556,42.222222,42.222222,33.333333,35.555556,24.444444,22.222222,22.222222,13.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,100.0,50.000000,52.272727,38.636364,50.000000,38.636364,34.090909,22.727273,36.363636,22.727273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,100.0,36.363636,31.818182,25.000000,27.272727,27.272727,20.454545,20.454545,13.636364,20.454545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11,100.0,45.714286,48.571429,37.142857,28.571429,34.285714,34.285714,22.857143,25.714286,28.571429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12,100.0,38.888889,35.185185,33.333333,25.925926,40.740741,16.666667,27.777778,29.629630,24.074074,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-01,100.0,23.214286,53.571429,28.571429,33.928571,30.357143,35.714286,28.571429,23.214286,37.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02,100.0,37.931034,41.379310,44.827586,29.310345,31.034483,31.034483,31.034483,34.482759,31.034483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03,100.0,38.333333,46.666667,33.333333,35.000000,25.000000,36.666667,41.666667,31.666667,28.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-04,100.0,32.075472,18.867925,26.415094,30.188679,32.075472,39.622642,30.188679,32.075472,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-05,100.0,25.000000,42.857143,25.000000,19.642857,26.785714,41.071429,28.571429,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-06,100.0,36.538462,36.538462,21.153846,38.461538,30.769231,30.769231,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-07,100.0,34.042553,25.531915,29.787234,34.042553,31.914894,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08,100.0,41.772152,43.037975,44.303797,37.974684,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09,100.0,43.939394,43.939394,25.757576,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10,100.0,54.411765,36.764706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11,100.0,34.920635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#churn driver analysis

In [97]:
#categorical churn analysis
categorical_drivers = [
    "gender",
    "region",
    "city_tier",
    "acquisition_channel",
    "loyalty_member",
    "preferred_device"
]

for column in categorical_drivers:
    print("\n" + "=" * 60)
    print(column.upper())
    
    analysis = (
        customer_master
        .groupby(column)
        .agg(
            customers=("customer_id", "nunique"),
            churned_customers=(
                "customer_status",
                lambda x: (x == "Churned").sum()
            )
        )
        .reset_index()
    )
    
    analysis["churn_rate"] = (
        analysis["churned_customers"]
        / analysis["customers"]
        * 100
    )
    
    print(analysis.sort_values("churn_rate", ascending=False))

============================================================
GENDER
   gender  customers  churned_customers  churn_rate
0  Female        853                387   45.369285
1    Male        969                403   41.589267

============================================================
REGION
    region  customers  churned_customers  churn_rate
3    South        553                246   44.484629
2    North        535                234   43.738318
0  Central        135                 59   43.703704
4     West        412                171   41.504854
1     East        215                 89   41.395349

============================================================
CITY_TIER
  city_tier  customers  churned_customers  churn_rate
2    Tier-3        263                130   49.429658
1    Tier-2        565                245   43.362832
0     Metro       1022                424   41.487280

============================================================
ACQUISITION_CHANNEL
  acquisition_channel  customers  churned_customers  churn_rate
1          Influencer        232                124   53.448276
3            Paid Ads        417                195   46.762590
5        Social Media        339                153   45.132743
0              Direct        236                102   43.220339
2      Organic Search        382                141   36.910995
4            Referral        244                 84   34.426230

============================================================
LOYALTY_MEMBER
  loyalty_member  customers  churned_customers  churn_rate
0             No       1353                641   47.376201
1            Yes        497                158   31.790744

============================================================
PREFERRED_DEVICE
  preferred_device  customers  churned_customers  churn_rate
2              iOS        424                189   44.575472
1          Desktop        374                161   43.048128
0          Android       1052                449   42.680608

In [98]:
# creating a purchasing-customer analysis
purchasing_customers = customer_master[
    customer_master["total_orders"] > 0
].copy()

print("Purchasing customers:", len(purchasing_customers))

Purchasing customers: 1668

In [99]:
#analyze each categorical data 
for column in categorical_drivers:
    print("\n" + "=" * 60)
    print(column.upper())
    
    analysis = (
        purchasing_customers
        .groupby(column)
        .agg(
            customers=("customer_id", "nunique"),
            churned_customers=(
                "customer_status",
                lambda x: (x == "Churned").sum()
            )
        )
        .reset_index()
    )
    
    analysis["churn_rate"] = (
        analysis["churned_customers"]
        / analysis["customers"]
        * 100
    )
    
    print(
        analysis
        .sort_values("churn_rate", ascending=False)
        .round(2)
    )

============================================================
GENDER
   gender  customers  churned_customers  churn_rate
0  Female        780                387       49.62
1    Male        863                403       46.70

============================================================
REGION
    region  customers  churned_customers  churn_rate
3    South        503                246       48.91
2    North        480                234       48.75
0  Central        123                 59       47.97
1     East        189                 89       47.09
4     West        373                171       45.84

============================================================
CITY_TIER
  city_tier  customers  churned_customers  churn_rate
2    Tier-3        234                130       55.56
1    Tier-2        511                245       47.95
0     Metro        923                424       45.94

============================================================
ACQUISITION_CHANNEL
  acquisition_channel  customers  churned_customers  churn_rate
1          Influencer        208                124       59.62
3            Paid Ads        376                195       51.86
5        Social Media        302                153       50.66
0              Direct        216                102       47.22
2      Organic Search        343                141       41.11
4            Referral        223                 84       37.67

============================================================
LOYALTY_MEMBER
  loyalty_member  customers  churned_customers  churn_rate
0             No       1214                641        52.8
1            Yes        454                158        34.8

============================================================
PREFERRED_DEVICE
  preferred_device  customers  churned_customers  churn_rate
2              iOS        382                189       49.48
0          Android        942                449       47.66
1          Desktop        344                161       46.80

In [100]:
#delivery delay as a churn driver 
purchasing_customers["delivery_delay_band"] = pd.cut(
    purchasing_customers["delivery_delay_rate"],
    bins=[-0.01, 10, 25, 50, 100],
    labels=[
        "0-10%",
        "10-25%",
        "25-50%",
        "50%+"
    ]
)

In [101]:
delivery_driver = (
    purchasing_customers
    .groupby("delivery_delay_band", observed=False)
    .agg(
        customers=("customer_id", "nunique"),
        churned_customers=(
            "customer_status",
            lambda x: (x == "Churned").sum()
        )
    )
    .reset_index()
)

delivery_driver["churn_rate"] = (
    delivery_driver["churned_customers"]
    / delivery_driver["customers"]
    * 100
)

delivery_driver.round(2)

  delivery_delay_band  customers  churned_customers  churn_rate
0               0-10%        549                322       58.65
1              10-25%        443                161       36.34
2              25-50%        493                204       41.38
3                50%+        183                112       61.20

In [102]:
#marketing engagement vs churn 
purchasing_customers["marketing_engaged"] = np.where(
    purchasing_customers["open_rate"] > 0,
    "Engaged",
    "Not Engaged"
)

In [103]:
marketing_driver = (
    purchasing_customers
    .groupby("marketing_engaged")
    .agg(
        customers=("customer_id", "nunique"),
        churned_customers=(
            "customer_status",
            lambda x: (x == "Churned").sum()
        )
    )
    .reset_index()
)

marketing_driver["churn_rate"] = (
    marketing_driver["churned_customers"]
    / marketing_driver["customers"]
    * 100
)

marketing_driver.round(2)

  marketing_engaged  customers  churned_customers  churn_rate
0           Engaged       1017                526       51.72
1       Not Engaged        651                273       41.94

In [ ]:
#At-Risk Customer Identification

In [104]:
#create risk segemnts
purchasing_customers["risk_segment"] = np.select(
    [
        purchasing_customers["days_since_last_purchase"] >= 60,
        purchasing_customers["days_since_last_purchase"] >= 30
    ],
    [
        "High Risk",
        "Medium Risk"
    ],
    default="Low Risk"
)

In [105]:
#create active at-risk customers
at_risk_customers = purchasing_customers[
    purchasing_customers["customer_status"] == "Active"
].copy()

at_risk_customers = at_risk_customers[
    at_risk_customers["days_since_last_purchase"] >= 30
]

In [106]:
at_risk_customers[
    [
        "customer_id",
        "customer_name",
        "days_since_last_purchase",
        "total_orders",
        "historical_clv",
        "delivery_delay_rate",
        "open_rate",
        "risk_segment"
    ]
].head(10)

,customer_id,customer_name,days_since_last_purchase,total_orders,historical_clv,delivery_delay_rate,open_rate,risk_segment
4,C0005,Bhavna Sethi,79.0,25.0,53772.05,20.000000,50.000000,High Risk
12,C0013,Pranav Khan,39.0,13.0,23617.25,30.769231,0.000000,Medium Risk
22,C0023,Jaya Shah,40.0,11.0,16173.50,9.090909,33.333333,Medium Risk
30,C0031,Ishaan Thakur,43.0,12.0,16415.30,16.666667,0.000000,Medium Risk
33,C0034,Komal Patil,59.0,10.0,8237.15,70.000000,66.666667,Medium Risk
38,C0039,Deepa Jain,42.0,11.0,13778.10,18.181818,25.000000,Medium Risk
39,C0040,Aarav Ahmed,44.0,13.0,20798.30,0.000000,33.333333,Medium Risk
56,C0057,Neha Deshmukh,59.0,17.0,52099.85,23.529412,33.333333,Medium Risk
59,C0060,Riya Singh,45.0,41.0,83906.00,17.073171,33.333333,Medium Risk
63,C0064,Esha Bhatia,42.0,14.0,38841.00,28.571429,50.000000,Medium Risk

In [107]:
#find high value at-risk customers 
high_value_at_risk = at_risk_customers[
    at_risk_customers["clv_segment"] == "High Value"
].sort_values(
    "historical_clv",
    ascending=False
)

In [108]:
high_value_at_risk[
    [
        "customer_id",
        "customer_name",
        "days_since_last_purchase",
        "total_orders",
        "historical_clv",
        "delivery_delay_rate",
        "open_rate",
        "risk_segment"
    ]
].head(20)

,customer_id,customer_name,days_since_last_purchase,total_orders,historical_clv,delivery_delay_rate,open_rate,risk_segment
109,C0110,Varun Banerjee,32.0,24.0,158980.70,37.500000,40.000000,Medium Risk
165,C0166,Ankit Siddiqui,58.0,35.0,127186.25,31.428571,40.000000,Medium Risk
171,C0172,Esha Bose,73.0,16.0,111889.30,25.000000,0.000000,High Risk
253,C0254,Deepa Pillai,32.0,38.0,95784.10,36.842105,50.000000,Medium Risk
215,C0216,Abhishek Nair,61.0,33.0,91121.40,24.242424,50.000000,High Risk
59,C0060,Riya Singh,45.0,41.0,83906.00,17.073171,33.333333,Medium Risk
70,C0071,Karan Chauhan,52.0,17.0,82832.00,17.647059,100.000000,Medium Risk
353,C0354,Arjun Mehta,56.0,16.0,82074.20,18.750000,50.000000,Medium Risk
1067,C1068,Rajesh Saxena,56.0,18.0,80564.55,22.222222,100.000000,Medium Risk
362,C0363,Anil Arora,30.0,37.0,80085.05,24.324324,0.000000,Medium Risk
105,C0106,Lakshmi Chatterjee,73.0,9.0,74836.40,22.222222,0.000000,High Risk
131,C0132,Aditya Menon,57.0,39.0,73415.95,15.384615,0.000000,Medium Risk
511,C0512,Imran Mahajan,35.0,30.0,69715.25,16.666667,0.000000,Medium Risk
937,C0938,Nisha Chatterjee,39.0,10.0,68991.10,20.000000,50.000000,Medium Risk
484,C0485,Meera Arora,83.0,17.0,68812.40,35.294118,33.333333,High Risk
311,C0312,Ramesh Agarwal,68.0,26.0,67617.25,19.230769,40.000000,High Risk
987,C0988,Aarav Rawat,53.0,14.0,65040.20,21.428571,0.000000,Medium Risk
111,C0112,Ashok Das,40.0,33.0,64227.70,45.454545,0.000000,Medium Risk
319,C0320,Anil Khan,45.0,19.0,61999.05,5.263158,33.333333,Medium Risk
331,C0332,Jaya Kapoor,72.0,15.0,61851.20,20.000000,0.000000,High Risk

In [109]:
#summarize the risk population 
risk_summary = (
    at_risk_customers
    .groupby("risk_segment")
    .agg(
        customers=("customer_id", "nunique"),
        total_historical_value=("historical_clv", "sum"),
        average_clv=("historical_clv", "mean"),
        average_days_since_purchase=(
            "days_since_last_purchase",
            "mean"
        )
    )
    .reset_index()
)

risk_summary

,risk_segment,customers,total_historical_value,average_clv,average_days_since_purchase
0,High Risk,148,2379472.30,16077.515541,74.155405
1,Medium Risk,308,5436472.15,17650.883604,42.795455

In [ ]:
#revenue at Risk & Win-Back Opportunity

In [110]:
#calcualte value active at-risk customers
at_risk_value = (
    at_risk_customers
    .groupby("risk_segment")
    .agg(
        customers=("customer_id", "nunique"),
        historical_value=("historical_clv", "sum"),
        average_customer_value=("historical_clv", "mean")
    )
    .reset_index()
)

at_risk_value

  risk_segment  customers  historical_value  average_customer_value
0    High Risk        148        2379472.30            16077.515541
1  Medium Risk        308        5436472.15            17650.883604

In [111]:
#calclate churned customer valye 
churned_customers = purchasing_customers[
    purchasing_customers["customer_status"] == "Churned"
].copy()

churned_value = (
    churned_customers
    .agg(
        churned_customers=("customer_id", "nunique"),
        total_churned_value=("historical_clv", "sum"),
        average_churned_value=("historical_clv", "mean")
    )
)

churned_value

                       customer_id  historical_clv
churned_customers            799.0             NaN
total_churned_value            NaN    9.207328e+06
average_churned_value          NaN    1.152356e+04

In [112]:
#create win back priority
at_risk_customers["winback_priority"] = np.select(
    [
        (
            (at_risk_customers["risk_segment"] == "High Risk") &
            (at_risk_customers["clv_segment"] == "High Value")
        ),
        (
            (at_risk_customers["risk_segment"] == "High Risk") &
            (at_risk_customers["clv_segment"] == "Medium Value")
        ),
        (
            (at_risk_customers["risk_segment"] == "Medium Risk") &
            (at_risk_customers["clv_segment"] == "High Value")
        )
    ],
    [
        "Critical",
        "High",
        "High"
    ],
    default="Standard"
)

In [113]:
#see the priority distribution 
at_risk_customers["winback_priority"].value_counts()

winback_priority
Standard    253
High        157
Critical     46
Name: count, dtype: int64

In [114]:
#create final list
winback_list = at_risk_customers[
    at_risk_customers["winback_priority"].isin(
        ["Critical", "High"]
    )
].sort_values(
    ["winback_priority", "historical_clv"],
    ascending=[True, False]
)

In [115]:
winback_list[
    [
        "customer_id",
        "customer_name",
        "days_since_last_purchase",
        "total_orders",
        "historical_clv",
        "delivery_delay_rate",
        "open_rate",
        "conversion_rate",
        "risk_segment",
        "clv_segment",
        "winback_priority"
    ]
].head(20)

,customer_id,customer_name,days_since_last_purchase,total_orders,historical_clv,delivery_delay_rate,open_rate,conversion_rate,risk_segment,clv_segment,winback_priority
171,C0172,Esha Bose,73.0,16.0,111889.30,25.000000,0.000000,0.0,High Risk,High Value,Critical
215,C0216,Abhishek Nair,61.0,33.0,91121.40,24.242424,50.000000,0.0,High Risk,High Value,Critical
105,C0106,Lakshmi Chatterjee,73.0,9.0,74836.40,22.222222,0.000000,0.0,High Risk,High Value,Critical
484,C0485,Meera Arora,83.0,17.0,68812.40,35.294118,33.333333,0.0,High Risk,High Value,Critical
311,C0312,Ramesh Agarwal,68.0,26.0,67617.25,19.230769,40.000000,0.0,High Risk,High Value,Critical
331,C0332,Jaya Kapoor,72.0,15.0,61851.20,20.000000,0.000000,0.0,High Risk,High Value,Critical
282,C0283,Mansi Sethi,61.0,23.0,55700.25,47.826087,60.000000,0.0,High Risk,High Value,Critical
717,C0718,Sana Ahmed,90.0,17.0,55308.25,35.294118,50.000000,0.0,High Risk,High Value,Critical
4,C0005,Bhavna Sethi,79.0,25.0,53772.05,20.000000,50.000000,0.0,High Risk,High Value,Critical
597,C0598,Mohit Nair,74.0,13.0,45309.40,15.384615,50.000000,0.0,High Risk,High Value,Critical
958,C0959,Naveen Tiwari,72.0,8.0,45201.65,37.500000,100.000000,0.0,High Risk,High Value,Critical
919,C0920,Ankit Bhatia,72.0,8.0,44740.05,50.000000,0.000000,0.0,High Risk,High Value,Critical
600,C0601,Naveen Bhatia,72.0,22.0,42296.90,27.272727,75.000000,25.0,High Risk,High Value,Critical
1050,C1051,Shubham Verma,62.0,8.0,41598.70,50.000000,0.000000,0.0,High Risk,High Value,Critical
899,C0900,Kunal Sethi,61.0,9.0,39795.00,22.222222,0.000000,0.0,High Risk,High Value,Critical
1292,C1293,Riya Chauhan,85.0,7.0,38401.85,28.571429,50.000000,0.0,High Risk,High Value,Critical
1047,C1048,Swati Yadav,67.0,6.0,37087.10,16.666667,100.000000,0.0,High Risk,High Value,Critical
1130,C1131,Aarav Sethi,80.0,5.0,37055.00,0.000000,100.000000,0.0,High Risk,High Value,Critical
1030,C1031,Rohini Arora,69.0,13.0,36655.10,46.153846,0.000000,0.0,High Risk,High Value,Critical
766,C0767,Mayank Kapoor,89.0,8.0,35260.00,0.000000,33.333333,0.0,High Risk,High Value,Critical

In [116]:
#calculate total value of priority customer s
priority_value = (
    winback_list["historical_clv"].sum()
)

priority_customers = (
    winback_list["customer_id"].nunique()
)

print("Priority customers:", priority_customers)
print("Historical value:", round(priority_value, 2))

Priority customers: 203
Historical value: 6200751.75

In [ ]:
#Final Customer Master + Business Summary

In [117]:
#chedck final customer master 
print("Rows:", customer_master.shape[0])
print("Columns:", customer_master.shape[1])

customer_master.head()

Rows: 1850
Columns: 44

,customer_id,customer_name,gender,age,email,city,state,region,city_tier,signup_date,...,total_marketing_cost,avg_discount_offered,open_rate,click_rate,conversion_rate,unsubscribe_rate,is_repeat_customer,historical_clv,clv_segment,first_purchase_month
0,C0001,Shweta Mishra,Female,38.0,shweta.mishra100@example.com,Bengaluru,Karnataka,South,Metro,2023-01-01,...,0.00,10.00,100.000000,0.0,0.0,0.0,1,19605.00,Medium Value,2023-01
1,C0002,Sneha Ali,Female,24.0,sneha.ali101@example.com,Bhopal,Madhya Pradesh,Central,Tier-2,2023-01-01,...,1.03,15.00,33.333333,0.0,0.0,0.0,1,17138.65,Medium Value,2023-01
2,C0003,Akash Trivedi,Male,35.0,akash.trivedi102@example.com,Lucknow,Uttar Pradesh,North,Tier-2,2023-01-01,...,1.28,13.75,50.000000,25.0,25.0,0.0,1,51265.75,High Value,2023-01
3,C0004,Radhika Pandey,Female,30.0,radhika.pandey103@example.com,Udaipur,Rajasthan,North,Tier-3,2023-01-02,...,1.83,19.00,40.000000,40.0,0.0,0.0,1,14641.95,Medium Value,2023-01
4,C0005,Bhavna Sethi,Female,22.0,bhavna.sethi104@example.com,Udaipur,Rajasthan,North,Tier-3,2023-01-03,...,1.21,15.00,50.000000,50.0,0.0,0.0,1,53772.05,High Value,2023-01

In [118]:
customer_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 1850 entries, 0 to 1849
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               1850 non-null   str
 1   customer_name             1850 non-null   str
 2   gender                    1822 non-null   str
 3   age                       1813 non-null   float64
 4   email                     1850 non-null   str
 5   city                      1850 non-null   str
 6   state                     1850 non-null   str
 7   region                    1850 non-null   str
 8   city_tier                 1850 non-null   str
 9   signup_date               1850 non-null   datetime64[us]
 10  acquisition_channel       1850 non-null   str
 11  email_opt_in              1832 non-null   str
 12  loyalty_member            1850 non-null   str
 13  preferred_device          1850 non-null   str
 14  total_orders              1850 non-null   float64
 15  total_quantity            1850 non-null   float64
 16  total_revenue             1850 non-null   float64
 17  average_order_value       1850 non-null   float64
 18  first_purchase_date       1668 non-null   datetime64[us]
 19  last_purchase_date        1668 non-null   datetime64[us]
 20  days_since_last_purchase  1668 non-null   float64
 21  churn_status              1668 non-null   str
 22  customer_status           1850 non-null   str
 23  total_deliveries          1850 non-null   float64
 24  delayed_deliveries        1850 non-null   float64
 25  avg_delivery_delay_days   1850 non-null   float64
 26  avg_delivery_rating       1850 non-null   float64
 27  avg_delivery_attempts     1850 non-null   float64
 28  delivery_delay_rate       1850 non-null   float64
 29  campaigns_received        1850 non-null   float64
 30  campaigns_opened          1850 non-null   float64
 31  campaigns_clicked         1850 non-null   float64
 32  campaigns_converted       1850 non-null   float64
 33  campaigns_unsubscribed    1850 non-null   float64
 34  total_marketing_cost      1850 non-null   float64
 35  avg_discount_offered      1850 non-null   float64
 36  open_rate                 1850 non-null   float64
 37  click_rate                1850 non-null   float64
 38  conversion_rate           1850 non-null   float64
 39  unsubscribe_rate          1850 non-null   float64
 40  is_repeat_customer        1850 non-null   int64
 41  historical_clv            1850 non-null   float64
 42  clv_segment               1850 non-null   str
 43  first_purchase_month      1668 non-null   period[M]
dtypes: datetime64[us](3), float64(24), int64(1), period[M](1), str(15)
memory usage: 857.4 KB

In [119]:
#overall bussiness summary 
business_summary = {
    "total_customers": customer_master["customer_id"].nunique(),
    
    "purchasing_customers": (
        customer_master["total_orders"] > 0
    ).sum(),
    
    "active_customers": (
        customer_master["customer_status"] == "Active"
    ).sum(),
    
    "churned_customers": (
        customer_master["customer_status"] == "Churned"
    ).sum(),
    
    "never_purchased_customers": (
        customer_master["customer_status"] == "Never Purchased"
    ).sum(),
    
    "total_revenue": customer_master["total_revenue"].sum(),
    
    "repeat_customers": (
        customer_master["is_repeat_customer"] == 1
    ).sum(),
    
    "at_risk_customers": len(at_risk_customers),
    
    "high_value_at_risk": len(high_value_at_risk),
    
    "priority_winback_customers": len(winback_list),
    
    "priority_historical_value": (
        winback_list["historical_clv"].sum()
    )
}

business_summary

{'total_customers': 1850,
 'purchasing_customers': np.int64(1668),
 'active_customers': np.int64(869),
 'churned_customers': np.int64(799),
 'never_purchased_customers': np.int64(182),
 'total_revenue': np.float64(25463212.95),
 'repeat_customers': np.int64(1392),
 'at_risk_customers': 456,
 'high_value_at_risk': 141,
 'priority_winback_customers': 203,
 'priority_historical_value': np.float64(6200751.75)}

In [120]:
#overall churn rate 
overall_churn_rate = (
    (
        purchasing_customers["customer_status"] == "Churned"
    ).sum()
    / len(purchasing_customers)
    * 100
)

print(
    "Overall Churn Rate:",
    round(overall_churn_rate, 2),
    "%"
)

Overall Churn Rate: 47.9 %

In [121]:
#create a clean kpi table 
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Customers",
        "Purchasing Customers",
        "Active Customers",
        "Churned Customers",
        "Never Purchased",
        "Overall Churn Rate",
        "Repeat Purchase Rate",
        "Total Revenue",
        "At-Risk Customers",
        "High-Value At-Risk Customers",
        "Priority Win-Back Customers",
        "Priority Historical Value"
    ],
    
    "Value": [
        customer_master["customer_id"].nunique(),
        len(purchasing_customers),
        (customer_master["customer_status"] == "Active").sum(),
        (customer_master["customer_status"] == "Churned").sum(),
        (customer_master["customer_status"] == "Never Purchased").sum(),
        round(overall_churn_rate, 2),
        round(repeat_purchase_rate, 2),
        round(customer_master["total_revenue"].sum(), 2),
        len(at_risk_customers),
        len(high_value_at_risk),
        len(winback_list),
        round(winback_list["historical_clv"].sum(), 2)
    ]
})

kpi_summary

                             KPI        Value
0                Total Customers      1850.00
1           Purchasing Customers      1668.00
2               Active Customers       869.00
3              Churned Customers       799.00
4                Never Purchased       182.00
5             Overall Churn Rate        47.90
6           Repeat Purchase Rate        83.45
7                  Total Revenue  25463212.95
8              At-Risk Customers       456.00
9   High-Value At-Risk Customers       141.00
10   Priority Win-Back Customers       203.00
11     Priority Historical Value   6200751.75

In [122]:
#finla columns 
print(customer_master.columns.tolist())

['customer_id', 'customer_name', 'gender', 'age', 'email', 'city', 'state', 'region', 'city_tier', 'signup_date', 'acquisition_channel', 'email_opt_in', 'loyalty_member', 'preferred_device', 'total_orders', 'total_quantity', 'total_revenue', 'average_order_value', 'first_purchase_date', 'last_purchase_date', 'days_since_last_purchase', 'churn_status', 'customer_status', 'total_deliveries', 'delayed_deliveries', 'avg_delivery_delay_days', 'avg_delivery_rating', 'avg_delivery_attempts', 'delivery_delay_rate', 'campaigns_received', 'campaigns_opened', 'campaigns_clicked', 'campaigns_converted', 'campaigns_unsubscribed', 'total_marketing_cost', 'avg_discount_offered', 'open_rate', 'click_rate', 'conversion_rate', 'unsubscribe_rate', 'is_repeat_customer', 'historical_clv', 'clv_segment', 'first_purchase_month']

In [ ]:
#Export Final Datasets

In [123]:
import os

processed_path = r"C:\Users\tania\Customer_Churn_Analysis\data\processed"

os.makedirs(processed_path, exist_ok=True)

In [124]:
#export customer master 
customer_master.to_csv(
    os.path.join(
        processed_path,
        "customer_master.csv"
    ),
    index=False
)

In [125]:
#exported cleaned orders
valid_orders.to_csv(
    os.path.join(
        processed_path,
        "valid_orders.csv"
    ),
    index=False
)

In [126]:
#export delivery data 
delivery_order_metrics.to_csv(
    os.path.join(
        processed_path,
        "delivery_order_metrics.csv"
    ),
    index=False
)

In [127]:
#marketing data 
marketing_clean.to_csv(
    os.path.join(
        processed_path,
        "marketing_clean.csv"
    ),
    index=False
)

In [128]:
#cohort retention 
cohort_retention.to_csv(
    os.path.join(
        processed_path,
        "cohort_retention.csv"
    ),
    index=False
)

In [129]:
#kpi summary
kpi_summary.to_csv(
    os.path.join(
        processed_path,
        "kpi_summary.csv"
    ),
    index=False
)

In [130]:
#winback list
winback_list.to_csv(
    os.path.join(
        processed_path,
        "winback_list.csv"
    ),
    index=False
)

In [131]:
#verify all files 
print("Processed files:")

for file in os.listdir(processed_path):
    print(file)

Processed files:
cohort_retention.csv
customer_master.csv
delivery_order_metrics.csv
kpi_summary.csv
marketing_clean.csv
valid_orders.csv
winback_list.csv

In [132]:
print(customer_master.shape)
print(customer_master["customer_id"].nunique())

(1850, 44)
1850

In [133]:
customer_master[
    customer_master["customer_id"].duplicated(keep=False)
][["customer_id"]].sort_values("customer_id")

Empty DataFrame
Columns: [customer_id]
Index: []

In [134]:
duplicate_ids = customer_master[
    customer_master["customer_id"].duplicated(keep=False)
]

print("Duplicate rows:", len(duplicate_ids))
print("Duplicate customer IDs:", duplicate_ids["customer_id"].nunique())

Duplicate rows: 0
Duplicate customer IDs: 0

In [135]:
import pandas as pd

csv_path = r"C:\Users\tania\Customer_Churn_Analysis\data\processed\customer_master.csv"

check_csv = pd.read_csv(csv_path)

print("CSV shape:", check_csv.shape)
print("Unique customer IDs:", check_csv["customer_id"].nunique())

CSV shape: (1850, 44)
Unique customer IDs: 1850

In [136]:
print("Missing customer_id:", customer_master["customer_id"].isna().sum())
print("Blank customer_id:", (customer_master["customer_id"].astype(str).str.strip() == "").sum())

Missing customer_id: 0
Blank customer_id: 0

In [137]:
print(customer_master["customer_id"].head(20).tolist())

['C0001', 'C0002', 'C0003', 'C0004', 'C0005', 'C0006', 'C0007', 'C0008', 'C0009', 'C0010', 'C0011', 'C0012', 'C0013', 'C0014', 'C0015', 'C0016', 'C0017', 'C0018', 'C0019', 'C0020']

In [138]:
for col in customer_master.columns:
    print(
        col,
        " | nulls:", customer_master[col].isna().sum(),
        " | dtype:", customer_master[col].dtype
    )

customer_id  | nulls: 0  | dtype: str
customer_name  | nulls: 0  | dtype: str
gender  | nulls: 28  | dtype: str
age  | nulls: 37  | dtype: float64
email  | nulls: 0  | dtype: str
city  | nulls: 0  | dtype: str
state  | nulls: 0  | dtype: str
region  | nulls: 0  | dtype: str
city_tier  | nulls: 0  | dtype: str
signup_date  | nulls: 0  | dtype: datetime64[us]
acquisition_channel  | nulls: 0  | dtype: str
email_opt_in  | nulls: 18  | dtype: str
loyalty_member  | nulls: 0  | dtype: str
preferred_device  | nulls: 0  | dtype: str
total_orders  | nulls: 0  | dtype: float64
total_quantity  | nulls: 0  | dtype: float64
total_revenue  | nulls: 0  | dtype: float64
average_order_value  | nulls: 0  | dtype: float64
first_purchase_date  | nulls: 182  | dtype: datetime64[us]
last_purchase_date  | nulls: 182  | dtype: datetime64[us]
days_since_last_purchase  | nulls: 182  | dtype: float64
churn_status  | nulls: 182  | dtype: str
customer_status  | nulls: 0  | dtype: str
total_deliveries  | nulls: 0  | dtype: float64
delayed_deliveries  | nulls: 0  | dtype: float64
avg_delivery_delay_days  | nulls: 0  | dtype: float64
avg_delivery_rating  | nulls: 0  | dtype: float64
avg_delivery_attempts  | nulls: 0  | dtype: float64
delivery_delay_rate  | nulls: 0  | dtype: float64
campaigns_received  | nulls: 0  | dtype: float64
campaigns_opened  | nulls: 0  | dtype: float64
campaigns_clicked  | nulls: 0  | dtype: float64
campaigns_converted  | nulls: 0  | dtype: float64
campaigns_unsubscribed  | nulls: 0  | dtype: float64
total_marketing_cost  | nulls: 0  | dtype: float64
avg_discount_offered  | nulls: 0  | dtype: float64
open_rate  | nulls: 0  | dtype: float64
click_rate  | nulls: 0  | dtype: float64
conversion_rate  | nulls: 0  | dtype: float64
unsubscribe_rate  | nulls: 0  | dtype: float64
is_repeat_customer  | nulls: 0  | dtype: int64
historical_clv  | nulls: 0  | dtype: float64
clv_segment  | nulls: 0  | dtype: str
first_purchase_month  | nulls: 182  | dtype: period[M]

In [139]:
print(customer_master.dtypes)

customer_id                            str
customer_name                          str
gender                                 str
age                                float64
email                                  str
city                                   str
state                                  str
region                                 str
city_tier                              str
signup_date                 datetime64[us]
acquisition_channel                    str
email_opt_in                           str
loyalty_member                         str
preferred_device                       str
total_orders                       float64
total_quantity                     float64
total_revenue                      float64
average_order_value                float64
first_purchase_date         datetime64[us]
last_purchase_date          datetime64[us]
days_since_last_purchase           float64
churn_status                           str
customer_status                        str
total_deliveries                   float64
delayed_deliveries                 float64
avg_delivery_delay_days            float64
avg_delivery_rating                float64
avg_delivery_attempts              float64
delivery_delay_rate                float64
campaigns_received                 float64
campaigns_opened                   float64
campaigns_clicked                  float64
campaigns_converted                float64
campaigns_unsubscribed             float64
total_marketing_cost               float64
avg_discount_offered               float64
open_rate                          float64
click_rate                         float64
conversion_rate                    float64
unsubscribe_rate                   float64
is_repeat_customer                   int64
historical_clv                     float64
clv_segment                            str
first_purchase_month             period[M]
dtype: object

In [142]:
print(
    customer_master[
        ["customer_id", "customer_name", "email", "city"]
    ]
    .astype(str)
    .map(len)
    .max()
)

customer_id       5
customer_name    18
email            34
city             14
dtype: int64

In [144]:
python_ids = set(customer_master["customer_id"].astype(str))

print("Python IDs:", len(python_ids))

Python IDs: 1850

In [146]:
import csv

csv_path = r"C:\Users\tania\Customer_Churn_Analysis\data\processed\customer_master.csv"

with open(csv_path, "r", encoding="utf-8") as f:
    rows = list(csv.reader(f))

print("Total CSV lines:", len(rows))
print("Header columns:", len(rows[0]))

from collections import Counter

row_lengths = Counter(len(row) for row in rows[1:])
print("Column count distribution:", row_lengths)

Total CSV lines: 1851
Header columns: 44
Column count distribution: Counter({44: 1850})

In [147]:
import csv
from collections import Counter

csv_path = r"C:\Users\tania\Customer_Churn_Analysis\data\processed\customer_master.csv"

with open(csv_path, "r", encoding="utf-8") as f:
    rows = list(csv.reader(f))

print("Total CSV lines:", len(rows))
print("Header columns:", len(rows[0]))
print("Column count distribution:", Counter(len(row) for row in rows[1:]))

Total CSV lines: 1851
Header columns: 44
Column count distribution: Counter({44: 1850})

In [148]:
import pandas as pd

csv_path = r"C:\Users\tania\Customer_Churn_Analysis\data\processed\customer_master.csv"

df = pd.read_csv(csv_path)

df["first_purchase_date"] = df["first_purchase_date"].replace("0000-00-00", "")
df["last_purchase_date"] = df["last_purchase_date"].replace("0000-00-00", "")

df.to_csv(csv_path, index=False, quoting=1)

print(df.shape)

(1850, 44)